### ISSUE TITLE
Fix setup scripts with new contracts node

### ISSUE THREAD

**Issue by forgetso** [prosopo/captcha#95]
Using substrate contracts node 0.25 returns this error when setting up provider and dapp. Seems like the queryInfo command used by contract package does not exist in the node.

```
ℹ Provider does not exist, registering...                                               prosopoenvironment 21:11:54
ℹ Connected to db                                                                       prosopoenvironment 21:11:54
› Setting stake amount to 1 UNIT                                                        prosopoenvironment 21:11:54
› Stake amount 1 UNIT                                                                   prosopoenvironment 21:11:54
› Setting send amount to 2 UNIT                                                         prosopoenvironment 21:11:54
› Sending funds from 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY to 5EjTA28bKSbFPPyMbUjNtArxyqjwq38r1BapVmLZShaqEedV Amount: 2 UNIT. Free balance: 1152919 UNIT
› Provider sent amount 2 UNIT at tx hash  0x646dd6e1d11b9d3319cfc2eb74db42adcb8a8f5499037bd21ff61775f28af60c
› Getting new contract instance with pair 5EjTA28bKSbFPPyMbUjNtArxyqjwq38r1BapVmLZShaqEedV nonce 0
ℹ    - providerRegister                                                                 prosopoenvironment 21:11:54
› Sending address:  5EjTA28bKSbFPPyMbUjNtArxyqjwq38r1BapVmLZShaqEedV           prosopocontractapi: prosopo 21:11:54

 WARN  The transactionPaymentApi.queryInfo runtime call is not available in your environment

  at Submittable.paymentInfo (/home/prosopo/captcha2/node_modules/@polkadot/api/cjs/submittable/createClass.js:115:15)
  at ProsopoContractMethods.<anonymous> (/home/prosopo/captcha2/packages/contract/src/contract/interface.ts:122:42)
  at Generator.next (<anonymous>)
  at fulfilled (/home/prosopo/captcha2/node_modules/tslib/tslib.js:164:62)
  at processTicksAndRejections (node:internal/process/task_queues:95:5)


********************* ERROR *********************

ProviderDoesNotExist ProsopoContractError@getProviderDetails: ProviderDoesNotExist
    at handleContractCallOutcomeErrors (/home/prosopo/captcha2/packages/contract/src/contract/helpers.ts:105:2)
    at ProsopoContractMethods.<anonymous> (/home/prosopo/captcha2/packages/contract/src/contract/interface.ts:311:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/prosopo/captcha2/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
index.js setup

```

**Comment by HughParry** [comment]
Query info function available need to look into it
